Repository sebastianbergmann/phpunit, pull requests merged in 2020-03, with the labels that each got.

#4130 Enhancement: Canonicalize JSON values in failure message
  src/Framework/Constraint/JsonMatches.php
  tests/unit/Framework/Constraint/JsonMatchesTest.php
Labels: feature/assertion, type/enhancement

#4145 Fix json diff failure issues (8.5)
  src/Framework/Constraint/JsonMatches.php
  src/Util/Json.php
  tests/unit/Framework/Constraint/JsonMatchesTest.php
Labels: type/bug

#4158 Enhancement: Update actions/checkout
  .github/workflows/ci.yml
Labels: type/build-automation

#4153 Enhancement: Update shivammathur/setup-php
  .github/workflows/ci.yml
Labels: type/build-automation

#4155 Enhancement: Let composer determine cache directory
  .github/workflows/ci.yml
Labels: type/build-automation

#4156 Fix: Consistently use shivammathur/setup-php
  .github/workflows/ci.yml
Labels: type/bug, type/build-automation

#4154 Fix: Configure COMPOSER_ROOT_VERSION
  .github/workflows/ci.yml
Labels: type/bug, type/build-automation

#3982 Windows build automation
  .github/workflows/ci.yml
Labels: type/build-automation
