Repository sebastianbergmann/phpunit, pull requests merged in 2024-01, with the labels that each got.

#5642 Command to print the list of test files
  src/TextUI/Application.php
  src/TextUI/Command/Commands/ListTestFilesCommand.php
  src/TextUI/Configuration/Cli/Builder.php
  src/TextUI/Configuration/Cli/Configuration.php
  src/TextUI/Help.php
  tests/end-to-end/_files/output-cli-help-color.txt
  tests/end-to-end/_files/output-cli-usage.txt
  tests/end-to-end/cli/list-file-tests/list-phpt-test-files.phpt
  tests/end-to-end/cli/list-file-tests/list-test-files-exclude-group.phpt
  tests/end-to-end/cli/list-file-tests/list-test-files-group.phpt
  tests/end-to-end/cli/list-file-tests/list-test-files.phpt
Labels: type/enhancement, feature/test-runner

#5654 9.6 logical not issue
  src/Framework/Constraint/Operator/LogicalNot.php
  tests/unit/Framework/Assert/AssertNotEqualsTest.php
Labels: type/bug, feature/assertion

#5685 Enhancement: Update `actions/upload-artifact` and `actions/download-artifact`
  .github/workflows/ci.yaml
Labels: type/build-automation
